# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#default skill type
SkillType.create(name: 'Acrobatics', modifier_type: 'dex', default: true)
SkillType.create(name: 'Appraise', modifier_type: 'int', default: true)
SkillType.create(name: 'Bluff', modifier_type: 'cha', default: true)
SkillType.create(name: 'Climb', modifier_type: 'str', default: true)
SkillType.create(name: 'Diplomacy', modifier_type: 'cha', default: true)
SkillType.create(name: 'Disable Device', modifier_type: 'dex', default: true)
SkillType.create(name: 'Disguise', modifier_type: 'cha', default: true)
SkillType.create(name: 'Escape Artist', modifier_type: 'dex', default: true)
SkillType.create(name: 'Fly', modifier_type: 'dex', default: true)
SkillType.create(name: 'Handle Animal', modifier_type: 'cha', default: true)
SkillType.create(name: 'Heal', modifier_type: 'wis', default: true)
SkillType.create(name: 'Intimidate', modifier_type: 'cha', default: true)
SkillType.create(name: 'Knowledge (arcana)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (dungeoneering)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (engineering)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (geography)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (history)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (local)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (nature)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (nobility)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (planes)', modifier_type: 'int', default: true)
SkillType.create(name: 'Knowledge (religion)', modifier_type: 'int', default: true)
SkillType.create(name: 'Linguistics', modifier_type: 'int', default: true)
SkillType.create(name: 'Perception', modifier_type: 'wis', default: true)
SkillType.create(name: 'Ride', modifier_type: 'dex', default: true)
SkillType.create(name: 'Sense Motive', modifier_type: 'wis', default: true)
SkillType.create(name: 'Sleight of Hand', modifier_type: 'dex', default: true)
SkillType.create(name: 'Spellcraft', modifier_type: 'int', default: true)
SkillType.create(name: 'Stealth', modifier_type: 'dex', default: true)
SkillType.create(name: 'Survival', modifier_type: 'wis', default: true)
SkillType.create(name: 'Swim', modifier_type: 'str', default: true)
SkillType.create(name: 'Use Magic Device', modifier_type: 'cha', default: true)